<!DOCTYPE html>
<html>
<head> 
<meta name="google-site-verification" content="V8YQiYmZMVQpJi9143Qa702duTPXz-oJFlAjS_tsFVs" />

<link rel="stylesheet" href="<?= SYSTEM_URL ?>/public/css/metro/css/metro-bootstrap.css">
<link rel="stylesheet" href="<?= SYSTEM_URL ?>/public/css/metro/css/style.css">
        <script src="<?= SYSTEM_URL ?>/public/css/metro/js/jquery/jquery.min.js"></script>
        <script src="<?= SYSTEM_URL ?>/public/css/metro/js/jquery/jquery.widget.min.js"></script>
        <script src="<?= SYSTEM_URL ?>/public/css/metro/js/metro/metro.min.js"></script>
		
	<link rel="profile" href="http://gmpg.org/xfn/11" />
<!--<link rel="stylesheet" type="text/css" media="all" href="http://themesdojo.com/metro/wp-content/themes/MetroTheme/style.css" />-->
<link rel="stylesheet" type="text/css"  href="http://themesdojo.com/metro/wp-content/themes/MetroTheme/blue.css" />
<link rel="stylesheet" type="text/css"  href="http://themesdojo.com/metro/wp-content/themes/MetroTheme/fonts/stylesheet.css" />
<link rel="pingback" href="http://themesdojo.com/metro/xmlrpc.php" />

<link rel="alternate" type="application/rss+xml" title="MetroTheme &raquo; Feed" href="http://themesdojo.com/metro/?feed=rss2" />
<link rel="alternate" type="application/rss+xml" title="MetroTheme &raquo; Comments Feed" href="http://themesdojo.com/metro/?feed=comments-rss2" />
<link rel='stylesheet' id='contact-form-7-css'  href='http://themesdojo.com/metro/wp-content/plugins/contact-form-7/includes/css/styles.css?ver=3.5.2' type='text/css' media='all' />
<script type='text/javascript' src='https://ajax.googleapis.com/ajax/libs/jquery/1.6.0/jquery.min.js?ver=3.6.1'></script>
<script type='text/javascript' src='http://themesdojo.com/metro/wp-includes/js/comment-reply.min.js?ver=3.6.1'></script>
<link rel="EditURI" type="application/rsd+xml" title="RSD" href="http://themesdojo.com/metro/xmlrpc.php?rsd" />
<link rel="wlwmanifest" type="application/wlwmanifest+xml" href="http://themesdojo.com/metro/wp-includes/wlwmanifest.xml" /> 
<meta name="generator" content="WordPress 3.6.1" />
<link rel='canonical' href='http://themesdojo.com/metro/?contact=contact' />
<script src="http://themesdojo.com/metro/wp-content/themes/MetroTheme/js/jquery-ui-1.8.11.custom.js"></script>
<script src="http://themesdojo.com/metro/wp-content/themes/MetroTheme/js/script.js"></script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-43776132-1', 'themedojo.com');
  ga('send', 'pageview');

</script>
	<?php
		
		// Check if dojo library is needed
		if ($this->dojo()->isEnabled()):
			// Include dojo library
			$this->dojo()->setLocalPath(SYSTEM_URL.'/public/dojo/dojo/dojo.js')
				// Use dojo theme tundra
				->addStyleSheetModule('dijit.themes.claro');
			// Echo out the dojo <script> tags
			echo $this->dojo();
		endif; 
	?>
</head>

<body class="metro claro" style="background-color: #efeae3">

<?php echo $this->layout()->content ?>	

</body>
</html>