<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd"> 
<html> 
<head> 
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="language" content="en" />
<?php
$this->headTitle(SYSTEM_NAME, 'APPEND');
$this->headTitle()->setSeparator(' - ');
echo $this->headTitle();

$front = Zend_Controller_Front::getInstance(); 
?>

</head>
<?php 
if(Zend_Auth::getInstance()->getIdentity())
	$page = SYSTEM_URL."/admin";
else
	$page = SYSTEM_URL."/authentication/login";

?>

<frameset bordercolor="#FFFFFF" rows="*" cols="*" border="0" frameborder="0" framespacing="0">
			<frame name="right" src="<?= $page ?>" noresize="noresize" scrolling="yes" />
	<noframes>
		Sorry, your browser does not handle frames!
	</noframes>
</frameset>
<noframes>
	Sorry, your browser does not handle frames!
</noframes>
</html>